export const NEW_ENQUIRY_REQUEST = "NEW_ENQUIRY_REQUEST";
export const NEW_ENQUIRY_SUCCESS = "NEW_ENQUIRY_SUCCESS";
export const NEW_ENQUIRY_RESET = "NEW_ENQUIRY_RESET";
export const NEW_ENQUIRY_FAIL = "NEW_ENQUIRY_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";